services:
  - type: web
    name: stroke-prediction-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        sync: false
        value: https://proyecto-ix-g3-data-scientist-ia-586b.onrender.com
    staticPublishPath: ./dist
    healthCheckPath: /
